# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Bernabe
title: Attempt of sysadmin
email: el@beroth.moe
website: https://b3rosu.github.io/cv.gitub.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: don't
github_username:  b3rosu
minecraft_server: beroth.moe
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: dev.beroth.moe
  icon: fas fa-globe
  url: https://dev.beroth.moe
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Sup I'm Bernabe and I work as a Jr. help desk / sysadmin. I have experience working with Linux and Windows server but what I like the most is Linux.

  I am most skilled in: <mark>Linux</mark> and <mark>playing videogames</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: My self hosted stuff
        link: beroth.moe
        # link_text: Project Website
        #additional_links:
        # - title:  sproogen/modern-resume-theme
        #   icon: fab fa-github
        #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is why I started to really be into linux, before this I was using ubuntu 💀
        description: | # this will include new lines to allow paragraphs
          I started to rent my first droplet about a year ago for a <mark>Server administration class</mark> and after that I know that I like servers. |
        The things I got are: 
          - Email whit exim & dovecot
          - Web page with nginx (before was apache)
          - A PBX with asterisk, I have to say that it's not very useful
          - Minecraft bedrock server
          - Matrix, like a self hosted discord (is down rn)
          - FTP

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: I won't post online where do I job
          #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Jr. Help desk and sysadmin
        caption: January 2023 - Present
        quote: >
          Solving 21st century problems by restarting the server
        description: | # this will include new lines to allow paragraphs
          I help people with IT/love related problems, also I manage the servers which is the funiest part.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CUCEI
        caption: 2021 - idk
        sub_title: BSc software engineering
        quote: >
          CUCEI is falling down, seriusly.
        description: | # this will include new lines to allow paragraphs
          While I study I'm in CUCEI and then I leave, It's fun most of the time.

          I spent a lot of my free time in the library doing HW but not this one, this one is made at home.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some of my interests are:
      - Anime
      - Gaming
      - Sleep


# Footer
footer_show_references: true
# references_title: References on request (Override references text)
references_title: . 

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
